spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:tarefasdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:tarefas}
    password: ${DB_PASSWORD:senha_forte}
  jpa:
    hibernate:
      ddl-auto: update   # dev: update | prod: validate + Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
